export class PartnerPreference {
    id: any;
    userid: any;
    heightMin: any;
    heightMax: any;
    ageMin: any;
    ageMax: any;
    religion: any;
    motherTongue: any;
    incomeRange: any;
    country: any;
    city: any;
    state: any;
    diet: any;
    smoke:any;
    drink:any;
    residentialstatus:any;
    education: any;
    occupation: any;
    employedIn: any;
    familyBasedOut: any;
    familySize: any;
    manglikStatus: any;
    maritalStatus: any;
    casteGroup: any;
    subCaste: any;
    casteNoBar: any;
    postedBy: any;
    faceCut: any;
    bodyType: any;
    transferLocation: any;
    hobbies: any;
    habits: any;
    isInterestedInSettlingAbroad: any;
    personLookingFor: any;
    healthIssues: any;
    profileCompletionPercentage: any;
    eyesightRequirement: any;
    sistersCount: any;
    brothersCount: any;
    preferredCity: any;
    familyBackground: any;
    profileHandleBY: any;
}
