export class User {
  id: any;
  userId: any;
  username: any;
  email: any;
  phoneNumber: any;
  password: any;
  confirmPassword: any;
  profileVisible!: boolean; 
  joinDate!: Date;
  heightMin: any;
  heightMax: any;
  ageMin: any;
  ageMax: any;
  religion: any;
  motherTongue: any;
  incomeRange: any;
  country: any;
  city: any;
  state: any;
  diet: any;
  education: any;
  occupation: any;
  profilePhoto: any;
  employedIn: any;
  familyBasedOut: any;
  familySize: any;
  manglikStatus: any;
  activityOnSite: any;
  maritalStatus: any;
  casteGroup: any;
  subCaste: any;
  isVerifiedProfile: any;
  casteNoBar: any;
  postedBy: any;
  isRecentlyJoined: any;
  isOnline: any;
  viewedProfiles: any;
  notViewedProfiles: any;
  faceCut: any;
  bodyType: any;
  transferLocation: any;
  hobbies: any;
  habits: any;
  isInterestedInSettlingAbroad: any;
  personLookingFor: any;
  healthIssues: any;
  profileCompletionPercentage: any;
  eyesightRequirement: any;
  sistersCount: any;
  brothersCount: any;
  preferredCity: any;
  familyBackground: any;
  createProfileFor: any;
  age: any;
  message: any;
  profileHandleBY: any;
  name: any;

  residential_status:any;
  horoscope:any;

}
